<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://relaxng.org/ns/structure/1.0"?>
<package format="3">
  <name>g1_wbc_cpp</name>
  <version>0.1.0</version>
  <description>Ban C++ cua WBC dong luc hoc giu thang bang cho Unitree G1</description>
  <maintainer email="hoangdc@todo.todo">hoangdc</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <depend>eigen</depend>
  <depend>pinocchio</depend>
  <depend>proxsuite</depend>
  <depend>yaml-cpp</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
